In [1]:
import pandas as pd

In [140]:
df = pd.read_excel('/contracts_plus_loses_dash_0409.xlsx')

In [141]:
# Заполняем пропуски в даных
# для Фамилии и имени заменяем на моду
df.middle_name = df.middle_name.fillna((df.middle_name.mode())[0])
df.first_name = df.first_name.fillna((df.middle_name.mode())[0])
# для потерь - id и сумма пропуски заполняем 0 и для имени заполняем как "нет потерь"
df.loss_payout_amt_USD = df.loss_payout_amt_USD.fillna(0)
df.loss_id = df.loss_id.fillna(0)
df.loss_name = df.loss_name.fillna('без потерь')

In [97]:
# итого нет пропущенных значений
missing_values_percent = ( (df.isna().sum() / len(df))* 100 ).sort_values(ascending=False)
missing_values_percent

contract_id            0.0
contract_num           0.0
loss_name              0.0
loss_id                0.0
sex                    0.0
age                    0.0
middle_name            0.0
first_name             0.0
last_name              0.0
insurance_amount       0.0
price                  0.0
country                0.0
duration               0.0
currency_name          0.0
contract_status        0.0
client_id              0.0
product_name           0.0
loss_payout_amt_USD    0.0
dtype: float64

In [142]:
# удаляем незначащие для выявления аномалий столбцы
df.drop(['contract_num', 'last_name', 'first_name', 'middle_name', 'loss_id'],  axis=1, inplace = True)

In [143]:
# для использования аномалий перекодируем все признаки - в числовые

df_onehot = df.copy()
from sklearn.preprocessing import OneHotEncoder

onehotencoder = OneHotEncoder(sparse = False)
encoded_df = pd.DataFrame(onehotencoder.fit_transform(df_onehot[['product_name']]))
encoded_df.columns = onehotencoder.get_feature_names_out()
df_onehot = df_onehot.join(encoded_df)
df_onehot.drop('product_name', axis = 1, inplace = True)

onehotencoder = OneHotEncoder(sparse = False)
encoded_df = pd.DataFrame(onehotencoder.fit_transform(df_onehot[['contract_status']]))
encoded_df.columns = onehotencoder.get_feature_names_out()
df_onehot = df_onehot.join(encoded_df)
df_onehot.drop('contract_status', axis = 1, inplace = True)

onehotencoder = OneHotEncoder(sparse = False)
encoded_df = pd.DataFrame(onehotencoder.fit_transform(df_onehot[['currency_name']]))
encoded_df.columns = onehotencoder.get_feature_names_out()
df_onehot = df_onehot.join(encoded_df)
df_onehot.drop('currency_name', axis = 1, inplace = True)

onehotencoder = OneHotEncoder(sparse = False)
encoded_df = pd.DataFrame(onehotencoder.fit_transform(df_onehot[['country']]))
encoded_df.columns = onehotencoder.get_feature_names_out()
df_onehot = df_onehot.join(encoded_df)
df_onehot.drop('country', axis = 1, inplace = True)

onehotencoder = OneHotEncoder(sparse = False)
encoded_df = pd.DataFrame(onehotencoder.fit_transform(df_onehot[['sex']]))
encoded_df.columns = onehotencoder.get_feature_names_out()
df_onehot = df_onehot.join(encoded_df)
df_onehot.drop('sex', axis = 1, inplace = True)

onehotencoder = OneHotEncoder(sparse = False)
encoded_df = pd.DataFrame(onehotencoder.fit_transform(df_onehot[['loss_name']]))
encoded_df.columns = onehotencoder.get_feature_names_out()
df_onehot = df_onehot.join(encoded_df)
df_onehot.drop('loss_name', axis = 1, inplace = True)

df_onehot

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,contract_id,client_id,duration,price,insurance_amount,age,loss_payout_amt_USD,product_name_Страхование путешественников,product_name_Страхование путешественников USD,contract_status_Действует,...,country_США,country_Сирия,country_Таиланд,country_Турция,country_Узбекистан,country_Франция,sex_F,sex_M,loss_name_Оказание медицинской помощи,loss_name_без потерь
0,21111219,10161870404,10,1096,2000000,20,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,21111381,1017159879,7,1918,5000000,55,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2,21112353,10161883357,10,1096,2000000,61,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,21113224,100766461,14,1534,2000000,25,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
4,21113292,10171604758,7,1918,5000000,33,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3706,31133782315,100649013,15,2466,3000000,22,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
3707,31133836775,1017151314,7,1918,5000000,33,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3708,31133933241,1006491844,15,2466,3000000,43,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
3709,3114463583,1006513037,30,4932,3000000,29,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
3710,3114463955,10171539646,7,1918,5000000,45,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0

In [144]:
from sklearn.neighbors import LocalOutlierFactor
from sklearn.ensemble import IsolationForest

In [145]:
# выявляем аномалии по методу LOF
clf = LocalOutlierFactor(n_neighbors=5)
pred = clf.fit_predict(df_onehot)

In [102]:
# для некоторых столбцов разница существенная
df_onehot[pred == -1].mean() - df_onehot.mean()

contract_id                                      4.416159e+08
duration                                         5.928271e+00
price                                            2.824369e+02
insurance_amount                                -4.874998e+05
age                                              7.317944e-01
loss_payout_amt_USD                              9.108376e+01
product_name_Страхование путешественников       -6.047113e-02
product_name_Страхование путешественников USD    6.047113e-02
contract_status_Действует                        2.086291e-02
contract_status_Завершен                        -2.086291e-02
currency_name_No_change                          6.047113e-02
currency_name_USD                               -6.047113e-02
country_Азербайджан                              7.632041e-03
country_Аргентина                               -1.184289e-02
country_Армения                                 -1.999073e-02
country_Беларусь                                 5.595080e-03
country_Болгария                                -7.695814e-03
country_Великобритания                           5.910190e-03
country_Германия                                 9.865947e-04
country_Грузия                                   3.737431e-02
country_Египет                                  -1.503525e-02
country_Индонезия                               -6.289072e-03
country_Иран                                    -7.380704e-03
country_Казахстан                                1.182038e-02
country_Канада                                  -9.029405e-03
country_ОАЭ                                     -8.097204e-03
country_США                                      6.047113e-02
country_Сирия                                   -2.425222e-03
country_Таиланд                                 -3.756562e-02
country_Турция                                   1.987819e-02
country_Узбекистан                              -1.254626e-02
country_Франция                                 -1.176974e-02
sex_F                                           -1.057870e-03
sex_M                                            1.057870e-03
loss_name_Оказание медицинской помощи            1.107574e-02
loss_name_без потерь                            -1.107574e-02
dtype: float64

In [146]:
(pred == -1).sum()

625

In [147]:
clf = IsolationForest()
pred_if = clf.fit_predict(df_onehot)
(pred_if == -1).sum()

285

In [148]:
# с помощью метода CLF найдено 556 аномалий и с помощью метода IF 161
df_anomaly = df_onehot[pred == -1]
df_noanomaly = df_onehot[pred != -1]
df_anomaly['anomaly'] = 1
df_noanomaly['anomaly'] = 0

<ipython-input-148-d4f3c6e06eaf>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_anomaly['anomaly'] = 1
<ipython-input-148-d4f3c6e06eaf>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_noanomaly['anomaly'] = 0

In [149]:
# соединяем полный фрейм
df_noanomaly = df_noanomaly.append(df_anomaly)

<ipython-input-149-58c96a15f8e1>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_noanomaly = df_noanomaly.append(df_anomaly)

In [150]:
df_noanomaly_join = df_noanomaly[['contract_id','client_id','anomaly']]
df_noanomaly_join

      contract_id    client_id  anomaly
0        21111219  10161870404        0
1        21111381   1017159879        0
2        21112353  10161883357        0
3        21113224    100766461        0
5        21114111    100651616        0
...           ...          ...      ...
3688  31131464354   1017111918        1
3701  31133354144   1017149313        1
3704  31133671497   1016163597        1
3707  31133836775   1017151314        1
3709   3114463583   1006513037        1

[3711 rows x 3 columns]

In [156]:
df_noanomaly_join.to_excel('contracts_plus_loses_dash_0409_anomaly.xlsx')